version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      # Installer Trivy
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

  pre_build:
    commands:
      # Variables
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - ECR_URI=266833220419.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_URI=$ECR_URI/bluegreen-production:$IMAGE_TAG
      - APP_VERSION=$(node -p "require('./app/package.json').version")
      - echo "Building $IMAGE_URI — APP_VERSION=$APP_VERSION"

      # Login ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI

      # Tests unitaires
      - cd app && npm ci && npm test
      - cd ..

  build:
    commands:
      # Build image Docker
      - docker build -t $IMAGE_URI .
      - docker tag $IMAGE_URI $ECR_URI/bluegreen-production:latest

      # Scan Trivy — bloque si CRITICAL ou HIGH
      - trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress $IMAGE_URI

  post_build:
    commands:
      # Push sur ECR seulement si Trivy est passé
      - docker push $IMAGE_URI
      - docker push $ECR_URI/bluegreen-production:latest

      # Injecter APP_VERSION dans taskdef.json
      - sed -i "s|<IMAGE_URI>|$IMAGE_URI|g" taskdef.json
      - sed -i "s|<APP_VERSION>|$APP_VERSION|g" taskdef.json

      - echo "Build terminé — image $IMAGE_URI"

artifacts:
  files:
    - imageDetail.json
    - appspec.yaml
    - taskdef.json